/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ParsedHand = IDL.Record({
  'result' : IDL.Float64,
  'street' : IDL.Text,
  'date' : IDL.Text,
  'actions' : IDL.Vec(IDL.Text),
  'handNumber' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Analysis = IDL.Record({
  'pfr' : IDL.Float64,
  'foldToCbet' : IDL.Float64,
  'threeBetPct' : IDL.Float64,
  'vpip' : IDL.Float64,
  'biggestMistakes' : IDL.Vec(IDL.Text),
});
export const HandHistory = IDL.Record({
  'id' : IDL.Text,
  'hands' : IDL.Vec(ParsedHand),
  'userId' : UserId,
  'analysis' : Analysis,
});
export const UserProfileSettings = IDL.Record({
  'evDisplay' : IDL.Bool,
  'soundEffects' : IDL.Bool,
  'showHints' : IDL.Bool,
  'evDetailLevel' : IDL.Text,
  'language' : IDL.Text,
  'animationSpeed' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const StatsPublic = IDL.Record({
  'sessionsPlayed' : IDL.Nat,
  'evSaved' : IDL.Float64,
  'accuracy' : IDL.Float64,
});
export const SettingsPublic = IDL.Record({
  'evDisplay' : IDL.Bool,
  'soundEffects' : IDL.Bool,
  'showHints' : IDL.Bool,
  'evDetailLevel' : IDL.Text,
  'language' : IDL.Text,
  'animationSpeed' : IDL.Nat,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'stats' : StatsPublic,
  'settings' : SettingsPublic,
});
export const SpotFilters = IDL.Record({
  'street' : IDL.Text,
  'betSizing' : IDL.Text,
  'boardTexture' : IDL.Text,
  'position' : IDL.Text,
  'stackSize' : IDL.Text,
});
export const EvData = IDL.Record({
  'action' : IDL.Text,
  'expectedValue' : IDL.Float64,
});
export const Card = IDL.Record({ 'rank' : IDL.Text, 'suit' : IDL.Text });
export const ActionFrequency = IDL.Record({
  'bet' : IDL.Float64,
  'call' : IDL.Float64,
  'fold' : IDL.Float64,
  'check' : IDL.Float64,
  'raise' : IDL.Float64,
});
export const RangeMatrix = IDL.Vec(ActionFrequency);
export const SolvedSpot = IDL.Record({
  'id' : IDL.Text,
  'filters' : SpotFilters,
  'street' : IDL.Text,
  'description' : IDL.Text,
  'evData' : EvData,
  'board' : IDL.Vec(Card),
  'ranges' : RangeMatrix,
  'positions' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addHandHistory' : IDL.Func([IDL.Vec(ParsedHand)], [HandHistory], []),
  'createOrUpdateUser' : IDL.Func(
      [UserProfileSettings],
      [UserProfilePublic],
      [],
    ),
  'getSpotById' : IDL.Func([IDL.Text], [IDL.Opt(SolvedSpot)], ['query']),
  'getUserHandHistory' : IDL.Func([], [IDL.Vec(HandHistory)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'listSpots' : IDL.Func(
      [IDL.Opt(SpotFilters)],
      [IDL.Vec(SolvedSpot)],
      ['query'],
    ),
  'searchSpots' : IDL.Func([IDL.Text], [IDL.Vec(SolvedSpot)], ['query']),
  'seedSampleSpots' : IDL.Func([], [], []),
  'updateUserStats' : IDL.Func([StatsPublic], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ParsedHand = IDL.Record({
    'result' : IDL.Float64,
    'street' : IDL.Text,
    'date' : IDL.Text,
    'actions' : IDL.Vec(IDL.Text),
    'handNumber' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Analysis = IDL.Record({
    'pfr' : IDL.Float64,
    'foldToCbet' : IDL.Float64,
    'threeBetPct' : IDL.Float64,
    'vpip' : IDL.Float64,
    'biggestMistakes' : IDL.Vec(IDL.Text),
  });
  const HandHistory = IDL.Record({
    'id' : IDL.Text,
    'hands' : IDL.Vec(ParsedHand),
    'userId' : UserId,
    'analysis' : Analysis,
  });
  const UserProfileSettings = IDL.Record({
    'evDisplay' : IDL.Bool,
    'soundEffects' : IDL.Bool,
    'showHints' : IDL.Bool,
    'evDetailLevel' : IDL.Text,
    'language' : IDL.Text,
    'animationSpeed' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const StatsPublic = IDL.Record({
    'sessionsPlayed' : IDL.Nat,
    'evSaved' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  const SettingsPublic = IDL.Record({
    'evDisplay' : IDL.Bool,
    'soundEffects' : IDL.Bool,
    'showHints' : IDL.Bool,
    'evDetailLevel' : IDL.Text,
    'language' : IDL.Text,
    'animationSpeed' : IDL.Nat,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'stats' : StatsPublic,
    'settings' : SettingsPublic,
  });
  const SpotFilters = IDL.Record({
    'street' : IDL.Text,
    'betSizing' : IDL.Text,
    'boardTexture' : IDL.Text,
    'position' : IDL.Text,
    'stackSize' : IDL.Text,
  });
  const EvData = IDL.Record({
    'action' : IDL.Text,
    'expectedValue' : IDL.Float64,
  });
  const Card = IDL.Record({ 'rank' : IDL.Text, 'suit' : IDL.Text });
  const ActionFrequency = IDL.Record({
    'bet' : IDL.Float64,
    'call' : IDL.Float64,
    'fold' : IDL.Float64,
    'check' : IDL.Float64,
    'raise' : IDL.Float64,
  });
  const RangeMatrix = IDL.Vec(ActionFrequency);
  const SolvedSpot = IDL.Record({
    'id' : IDL.Text,
    'filters' : SpotFilters,
    'street' : IDL.Text,
    'description' : IDL.Text,
    'evData' : EvData,
    'board' : IDL.Vec(Card),
    'ranges' : RangeMatrix,
    'positions' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addHandHistory' : IDL.Func([IDL.Vec(ParsedHand)], [HandHistory], []),
    'createOrUpdateUser' : IDL.Func(
        [UserProfileSettings],
        [UserProfilePublic],
        [],
      ),
    'getSpotById' : IDL.Func([IDL.Text], [IDL.Opt(SolvedSpot)], ['query']),
    'getUserHandHistory' : IDL.Func([], [IDL.Vec(HandHistory)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'listSpots' : IDL.Func(
        [IDL.Opt(SpotFilters)],
        [IDL.Vec(SolvedSpot)],
        ['query'],
      ),
    'searchSpots' : IDL.Func([IDL.Text], [IDL.Vec(SolvedSpot)], ['query']),
    'seedSampleSpots' : IDL.Func([], [], []),
    'updateUserStats' : IDL.Func([StatsPublic], [], []),
  });
};

export const init = ({ IDL }) => { return []; };