/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActionFrequency {
  'bet' : number,
  'call' : number,
  'fold' : number,
  'check' : number,
  'raise' : number,
}
export interface Analysis {
  'pfr' : number,
  'foldToCbet' : number,
  'threeBetPct' : number,
  'vpip' : number,
  'biggestMistakes' : Array<string>,
}
export interface Card { 'rank' : string, 'suit' : string }
export interface EvData { 'action' : string, 'expectedValue' : number }
export interface HandHistory {
  'id' : string,
  'hands' : Array<ParsedHand>,
  'userId' : UserId,
  'analysis' : Analysis,
}
export interface ParsedHand {
  'result' : number,
  'street' : string,
  'date' : string,
  'actions' : Array<string>,
  'handNumber' : string,
}
export type RangeMatrix = Array<ActionFrequency>;
export interface SettingsPublic {
  'evDisplay' : boolean,
  'soundEffects' : boolean,
  'showHints' : boolean,
  'evDetailLevel' : string,
  'language' : string,
  'animationSpeed' : bigint,
}
export interface SolvedSpot {
  'id' : string,
  'filters' : SpotFilters,
  'street' : string,
  'description' : string,
  'evData' : EvData,
  'board' : Array<Card>,
  'ranges' : RangeMatrix,
  'positions' : Array<string>,
}
export interface SpotFilters {
  'street' : string,
  'betSizing' : string,
  'boardTexture' : string,
  'position' : string,
  'stackSize' : string,
}
export interface StatsPublic {
  'sessionsPlayed' : bigint,
  'evSaved' : number,
  'accuracy' : number,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'createdAt' : Timestamp,
  'stats' : StatsPublic,
  'settings' : SettingsPublic,
}
export interface UserProfileSettings {
  'evDisplay' : boolean,
  'soundEffects' : boolean,
  'showHints' : boolean,
  'evDetailLevel' : string,
  'language' : string,
  'animationSpeed' : bigint,
}
export interface _SERVICE {
  'addHandHistory' : ActorMethod<[Array<ParsedHand>], HandHistory>,
  'createOrUpdateUser' : ActorMethod<[UserProfileSettings], UserProfilePublic>,
  'getSpotById' : ActorMethod<[string], [] | [SolvedSpot]>,
  'getUserHandHistory' : ActorMethod<[], Array<HandHistory>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'listSpots' : ActorMethod<[[] | [SpotFilters]], Array<SolvedSpot>>,
  'searchSpots' : ActorMethod<[string], Array<SolvedSpot>>,
  'seedSampleSpots' : ActorMethod<[], undefined>,
  'updateUserStats' : ActorMethod<[StatsPublic], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];