/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Card {
    rank: string;
    suit: string;
}
export interface SettingsPublic {
    evDisplay: boolean;
    soundEffects: boolean;
    showHints: boolean;
    evDetailLevel: string;
    language: string;
    animationSpeed: bigint;
}
export interface HandHistory {
    id: string;
    hands: Array<ParsedHand>;
    userId: UserId;
    analysis: Analysis;
}
export interface Analysis {
    pfr: number;
    foldToCbet: number;
    threeBetPct: number;
    vpip: number;
    biggestMistakes: Array<string>;
}
export interface StatsPublic {
    sessionsPlayed: bigint;
    evSaved: number;
    accuracy: number;
}
export interface ParsedHand {
    result: number;
    street: string;
    date: string;
    actions: Array<string>;
    handNumber: string;
}
export interface SolvedSpot {
    id: string;
    filters: SpotFilters;
    street: string;
    description: string;
    evData: EvData;
    board: Array<Card>;
    ranges: RangeMatrix;
    positions: Array<string>;
}
export interface UserProfilePublic {
    id: UserId;
    createdAt: Timestamp;
    stats: StatsPublic;
    settings: SettingsPublic;
}
export type UserId = Principal;
export interface SpotFilters {
    street: string;
    betSizing: string;
    boardTexture: string;
    position: string;
    stackSize: string;
}
export interface UserProfileSettings {
    evDisplay: boolean;
    soundEffects: boolean;
    showHints: boolean;
    evDetailLevel: string;
    language: string;
    animationSpeed: bigint;
}
export type RangeMatrix = Array<ActionFrequency>;
export interface EvData {
    action: string;
    expectedValue: number;
}
export interface ActionFrequency {
    bet: number;
    call: number;
    fold: number;
    check: number;
    raise: number;
}
export interface backendInterface {
    addHandHistory(hands: Array<ParsedHand>): Promise<HandHistory>;
    createOrUpdateUser(settings: UserProfileSettings): Promise<UserProfilePublic>;
    getSpotById(id: string): Promise<SolvedSpot | null>;
    getUserHandHistory(): Promise<Array<HandHistory>>;
    getUserProfile(): Promise<UserProfilePublic | null>;
    listSpots(filters: SpotFilters | null): Promise<Array<SolvedSpot>>;
    searchSpots(searchQuery: string): Promise<Array<SolvedSpot>>;
    seedSampleSpots(): Promise<void>;
    updateUserStats(stats: StatsPublic): Promise<void>;
}
import type { SolvedSpot as _SolvedSpot, SpotFilters as _SpotFilters, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addHandHistory(arg0: Array<ParsedHand>): Promise<HandHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.addHandHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHandHistory(arg0);
            return result;
        }
    }
    async createOrUpdateUser(arg0: UserProfileSettings): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUser(arg0);
            return result;
        }
    }
    async getSpotById(arg0: string): Promise<SolvedSpot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpotById(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpotById(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserHandHistory(): Promise<Array<HandHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserHandHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserHandHistory();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSpots(arg0: SpotFilters | null): Promise<Array<SolvedSpot>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSpots(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSpots(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchSpots(arg0: string): Promise<Array<SolvedSpot>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSpots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSpots(arg0);
            return result;
        }
    }
    async seedSampleSpots(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleSpots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleSpots();
            return result;
        }
    }
    async updateUserStats(arg0: StatsPublic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserStats(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SolvedSpot]): SolvedSpot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpotFilters | null): [] | [_SpotFilters] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
